@@include('files/regular.js', {})
@@include('files/functions.js', {})
@@include('files/forms.js', {})
@@include('files/sliders.js', {})
@@include('files/scroll.js', {})
@@include('files/lazyload.js', {})