@@include('libs/vanila-lazyload.min.js', {})
@@include('libs/datepicker-full.min.js', {})
@@include('libs/smoothScroll.js', {})
@@include('libs/inputmask.min.js', {})
@@include('libs/swiper.min.js', {})